In [1]:
class Student:
    pass

In [2]:
s1=Student()

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error

In [ ]:
error >> |yact-ypred|

In [4]:
df=pd.read_csv('insurance.csv')

In [5]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [16]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [11]:
df.duplicated().sum()

1

In [ ]:
3 > 7 > 9

In [14]:
df.drop_duplicates(keep='first',inplace=True)

In [15]:
df.duplicated().sum()

0

In [18]:
df.replace({'male':0,'female':1},inplace=True)

In [19]:
df.replace(to_replace=['yes','no'],value=[1,0],inplace=True)

In [20]:
df.tail()

age  sex    bmi  children  smoker     region     charges
1333   50    0  30.97         3       0  northwest  10600.5483
1334   18    1  31.92         0       0  northeast   2205.9808
1335   18    1  36.85         0       0  southeast   1629.8335
1336   21    1  25.80         0       0  southwest   2007.9450
1337   61    1  29.07         0       1  northwest  29141.3603

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1337 non-null   int64  
 1   sex       1337 non-null   int64  
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64  
 4   smoker    1337 non-null   int64  
 5   region    1337 non-null   object 
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(4), object(1)
memory usage: 83.6+ KB


In [24]:
df=df.astype({'age':np.int16,'sex':np.int32, 'bmi':np.int32, 'children':np.int32, 'smoker':np.int32})

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1337 non-null   int16  
 1   sex       1337 non-null   int32  
 2   bmi       1337 non-null   int32  
 3   children  1337 non-null   int32  
 4   smoker    1337 non-null   int32  
 5   region    1337 non-null   object 
 6   charges   1337 non-null   float64
dtypes: float64(1), int16(1), int32(4), object(1)
memory usage: 54.8+ KB


In [27]:
X=df.drop(['region','charges'],axis=1)

In [46]:
y=df['charges'].values.reshape(-1,1).astype('int')

In [48]:
X.shape
y.shape

(1337, 1)

In [49]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.75,random_state=8)

In [50]:
lr=LinearRegression()

In [51]:
lr.fit(X_train,y_train)

LinearRegression()

In [53]:
lr.predict([[59,1,35,0,0]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[14291.48640116]])

In [52]:
df.sample(1)

age  sex  bmi  children  smoker     region    charges
654   59    1   35         0       0  southeast  12244.531

In [54]:
y_pred=lr.predict(X_test)

In [55]:
r2_score(y_test,y_pred)

0.7249178139240691

In [59]:
mean_squared_error(y_test,y_pred)**0.5

6264.5038843185275

In [60]:
mean_absolute_error(y_test,y_pred)

4368.296573876956

In [61]:
mean_absolute_percentage_error(y_test,y_pred)

0.4272701721415357

In [62]:
lr.intercept_

array([-11206.98679527])

In [63]:
lr.coef_

array([[  250.33648285,   156.73356553,   302.05391837,   453.51330792,
        24436.69964477]])

In [64]:
X

age  sex  bmi  children  smoker
0      19    1   27         0       1
1      18    0   33         1       0
2      28    0   33         3       0
3      33    0   22         0       0
4      32    0   28         0       0
...   ...  ...  ...       ...     ...
1333   50    0   30         3       0
1334   18    1   31         0       0
1335   18    1   36         0       0
1336   21    1   25         0       0
1337   61    1   29         0       1

[1337 rows x 5 columns]