In [45]:
class LR:
    
    def __init__(self):
        self.m=None
        self.c=None
    
    def fit(self,X_train,y_train):
        #num=sum(xi-x.mean)*(yi-ymean)
        #den=sum(sum(xi-x.mean)**2)
        #c=ymean -mxmean
        
        num=0
        den=0
        for i in range(X_train.shape[0]): #(1331,8)
            num=num+(X_train[i]-X_train.mean())*(y_train[i]-y_train.mean())
            den=den+(X_train[i]-X_train.mean())**2
        
        self.m=num/den
        self.c= y_train.mean() - (self.m*X_train.mean())
        
        print('Slope is ',self.m)
        print('Intercept is ',self.c)
    
    def predict(self,X_test):
        return (self.m*X_test) + self.c

In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [47]:
df=pd.read_csv('score.csv')

In [48]:
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [49]:
X=df.iloc[:,0].values.reshape(-1,1)
y=df.iloc[:,1].values.reshape(-1,1)

In [50]:
X
y

array([[21],
       [47],
       [27],
       [75],
       [30],
       [20],
       [88],
       [60],
       [81],
       [25],
       [85],
       [62],
       [41],
       [42],
       [17],
       [95],
       [30],
       [24],
       [67],
       [69],
       [30],
       [54],
       [35],
       [76],
       [86]], dtype=int64)

In [51]:
X_train,X_test,y_train,y_text=train_test_split(X,y,test_size=0.2,random_state=1)

In [52]:
lr=LR()

In [53]:
lr.fit(X_train,y_train)

Slope is  [10.46110829]
Intercept is  [-1.53695733]


In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
lr1=LinearRegression()

In [56]:
lr1.fit(X_train,y_train)

LinearRegression()

In [57]:
print("Slope from sklearn LR",lr1.coef_)
print("Slope from our LR",lr.m)
print("Intercept from sklearn LR",lr1.intercept_)
print("Intercept from our LR",lr.c)

Slope from sklearn LR [[10.46110829]]
Slope from our LR [10.46110829]
Intercept from sklearn LR [-1.53695733]
Intercept from our LR [-1.53695733]


In [58]:
lr.predict([2.5])

array([24.6158134])

In [59]:
lr1.predict([[2.5]])

array([[24.6158134]])